import React from "react";

export const HelpAndServices = () => {
  return (
    <div className="w-full h-auto bg-[#F1F3F6]  pt-0 p-48 text-justify">
      <div className="w-full h-auto bg-[#ffffff] pt-36  p-8">
        <h1 className="text-3xl font-[600]">Conditions of Use </h1>
        <br />
        <p>
          <b>Disclaimer:</b> In the event of any discrepancy or conflict, the
          English version will prevail over the translation.
        </p>
        <br />
        <p>
          The website www.shopcart.in ("Shopcart.in") is operated by Shopcart
          Seller Services Private Limited ("Shopcart" or "us" or "we" or "our"),
          having its registered office located 8th Floor, Brigade Gateway 26/1
          Dr. Rajkumar Road Bangalore – 560055, Karnataka, India. Please read
          the Conditions of Use document carefully before using the Shopcart.in
          website. By using the Shopcart.in website, you signify your agreement
          to be bound by Shopcart's Conditions of Use. Shopcart Europe Core
          SARL, Shopcart EU SARL, Shopcart Services Europe SARL and Shopcart
          Media EU SARL, all four at 38 avenue John F. Kennedy, L-1855,
          Luxembourg and Shopcart Digital UK Limited of 1 Principal Place,
          Worship Street, London, EC2A 2FA, UK (together "Shopcart Europe") are
          data controllers of personal information collected and processed
          through Shopcart Services. Details can be found here. As described in
          our Privacy Notice, we share information with Shopcart.com, Inc. and
          the subsidiaries that Shopcart.com, Inc. controls that are either
          subject to our Privacy Notice or follow practices at least as
          protective as those described in our Privacy Notice. We also share
          information with third-party service providers. For example, we use
          third-party service providers to fulfil orders for products or
          services, and to deliver packages. For any further details on our
          security practices please read our Privacy Notice. For any queries or
          issues relating to Shopcart.in, you can contact us by clicking
          www.shopcart.in/gp/help/contact-us
        </p>
        <br />
        <hr />
        <br />
        <p>
          Please read these conditions carefully before using the Shopcart.in
          website. By using the Shopcart.in website, you signify your agreement
          to be bound by these conditions. <br /> <br />
          In addition, when you use any current or future Shopcart.in service
          (eg. Wish List or Marketplace) ("Shopcart Service"), you will also be
          subject to the terms, guidelines and conditions applicable to that
          Shopcart Service. ("Terms"). If these Conditions of Use are
          inconsistent with such Terms, the Terms will control. <br /> <br /> These
          "Conditions of Use" constitute an electronic record within the meaning
          of the applicable law. This electronic record is generated by a
          computer system and does not require any physical or digital
          signatures.
        </p>
        <br />
        <li className="ml-3">Conditions Relating to Your Use of Shopcart.in</li>
        <li className="ml-3">
          Notice and Procedure for Making Claims of Infringement{" "}
        </li>
        <li className="ml-3">
          Notice and Procedure for Notifying Shopcart.in of Objectionable
          Content
        </li>
      </div>
    </div>
  );
};
